### ISSUE TITLE
代码中出现全角字符bug

### ISSUE THREAD

**Issue by IlluminateDarkheat** [Aiayw/OpenAI-APIKey-Query#4]
最新的 [commit](https://github.com/Aiayw/OpenAI-APIKey-Query/commit/11b822096b21f5977de8867a9510af70b71155e8) 中，140 行后的代码都使用了全角的 `，` 和 `。`

**Comment by Aiayw** [comment]
感谢反馈，应该是自动文本优化导致的，已修复。
